### ISSUE TITLE
AEAD mode with detached tag

### ISSUE THREAD

**Issue by stouset** [jedisct1/libsodium#350] opened 2016-01-27 08:56 UTC
It'd be nice if the AEAD modes offered had an analogue to the `_detached` secretbox functions, where the tag can be stored separately. I have a use-case in Rust where I'm encrypting the contents of an arbitrary type, and have no way of creating a variable pointing to `sizeof(T) + MACBYTES` bytes of memory.

**Comment by jedisct1** [comment] 2016-01-27 17:35
That's definitely in the TODO list!

**Comment by jedisct1** [comment] 2016-01-27 17:35
Duplicate of #324

**Closed by jedisct1** 2016-01-27 17:35 UTC

**Comment by jedisct1** [comment] 2016-01-27 17:36
Suggestions regarding the padding would also be welcome.

This is not an issue with the current constructions, but the API should support future constructions that may require padding.

**Comment by stouset** [comment] 2016-01-27 18:41
Have an extra `_PADDINGBYTES` constant, require another parameter capable of storing that many bytes of padding?
