### ISSUE TITLE
invalid usage on iOS when running crypto_pwhash

### ISSUE THREAD

**Issue by catsigma** [jedisct1/libsodium#695] opened 2018-03-13 14:00 UTC
```
sodium.crypto_pwhash(
      64,
      'aaa',
      'qqqqqqqqqqqqqqqw',
      10,
      1024 * 8,
      sodium.crypto_pwhash_ALG_ARGON2ID13)
```

This piece code works fine on desktop browsers, but not in the safari on iOS.

**Comment by jedisct1** [comment] 2018-03-13 15:01
Probably a duplicate of https://github.com/jedisct1/libsodium.js/issues/139

**Closed by jedisct1** 2018-03-13 15:01 UTC
