### ISSUE TITLE
several tests fail with coredumps

### ISSUE THREAD

**Issue by silpol** [jedisct1/libsodium#366] opened 2016-02-29 05:40 UTC
just fetched source code form HEAD and tried to build with _./autogen.sh_ and _make_ and _make check_
got several fails:

**Comment by silpol** [comment] 2016-02-29 05:42
`
==================================================
   libsodium 1.0.9: test/default/test-suite.log
==================================================

# TOTAL: 59
# PASS:  41
# SKIP:  0
# XFAIL: 0
# FAIL:  18
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: box
=========

FAIL: box2
==========

FAIL: box7
==========

FAIL: box8
==========

FAIL: box_easy
==============

FAIL: box_easy2
===============

FAIL: box_seal
==============

FAIL: randombytes
=================

FAIL: secretbox
===============

FAIL: secretbox2
================

FAIL: secretbox7
================

FAIL: secretbox8
================

FAIL: secretbox_easy
====================

FAIL: secretbox_easy2
=====================

FAIL: stream
============

FAIL: stream2
=============

FAIL: stream3
=============

FAIL: stream4
=============
`

**Comment by silpol** [comment] 2016-02-29 05:43
all sub-test log files have length zero
actual screen log looks like this

`PASS: aead_aes256gcm
PASS: aead_chacha20poly1305
PASS: auth
PASS: auth2
PASS: auth3
PASS: auth5
PASS: auth6
PASS: auth7
../../build-aux/test-driver: line 107: 15359 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box
../../build-aux/test-driver: line 107: 15384 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box2
../../build-aux/test-driver: line 107: 15409 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box7
../../build-aux/test-driver: line 107: 15434 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box8
../../build-aux/test-driver: line 107: 15459 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box_easy
../../build-aux/test-driver: line 107: 15484 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box_easy2
../../build-aux/test-driver: line 107: 15509 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: box_seal
PASS: box_seed
PASS: chacha20
PASS: core1
PASS: core2
PASS: core3
PASS: core4
PASS: core5
PASS: core6
PASS: ed25519_convert
PASS: generichash
PASS: generichash2
PASS: generichash3
PASS: hash
PASS: hash3
PASS: onetimeauth
PASS: onetimeauth2
PASS: onetimeauth7
PASS: pwhash_argon2i
PASS: pwhash_scrypt
PASS: pwhash_scrypt_ll
../../build-aux/test-driver: line 107: 16016 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: randombytes
PASS: scalarmult
PASS: scalarmult2
PASS: scalarmult5
PASS: scalarmult6
PASS: scalarmult7
../../build-aux/test-driver: line 107: 16161 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: secretbox
../../build-aux/test-driver: line 107: 16186 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: secretbox2
../../build-aux/test-driver: line 107: 16211 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: secretbox7
../../build-aux/test-driver: line 107: 16236 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: secretbox8
../../build-aux/test-driver: line 107: 16261 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: secretbox_easy
../../build-aux/test-driver: line 107: 16286 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: secretbox_easy2
PASS: shorthash
PASS: sign
PASS: sodium_core
PASS: sodium_utils
PASS: sodium_version
../../build-aux/test-driver: line 107: 16434 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: stream
../../build-aux/test-driver: line 107: 16459 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: stream2
../../build-aux/test-driver: line 107: 16484 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: stream3
../../build-aux/test-driver: line 107: 16509 Segmentation fault      (core dumped) "$@" > $log_file 2>&1
FAIL: stream4
PASS: verify1
PASS: sodium_utils2
PASS: sodium_utils3
make[5]: Entering directory `/tmp/libsodium/test/default'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/tmp/libsodium/test/default'
============================================================================
Testsuite summary for libsodium 1.0.9
============================================================================
# TOTAL: 59
# PASS:  41
# SKIP:  0
# XFAIL: 0
# FAIL:  18
# XPASS: 0
# ERROR: 0
============================================================================
See test/default/test-suite.log
Please report to https://github.com/jedisct1/libsodium/issues
============================================================================
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory `/tmp/libsodium/test/default'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory `/tmp/libsodium/test/default'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/tmp/libsodium/test/default'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/tmp/libsodium/test'
make: *** [check-recursive] Error 1`

**Comment by jedisct1** [comment] 2016-02-29 08:57
Hi, and thanks for reporting this.

What OS did you run that on?

Looks like the issue is actually with accessing `/dev/random`.

Can you post the content of the `config.log` file in a gist?

**Comment by jedisct1** [comment] 2016-02-29 11:10
Likely to be fixed in 0868222732a0f548f44801a196dfe71d33462e70

**Closed by jedisct1** 2016-02-29 11:10 UTC
