### ISSUE TITLE
Support for post-quantum schemes from the NIST standards?

### ISSUE THREAD

**Issue by niekbouman** [jedisct1/libsodium#1433] opened 2024-12-12 14:55 UTC
Back in August NIST has published its post-quantum standards: https://www.nist.gov/news-events/news/2024/08/nist-releases-first-3-finalized-post-quantum-encryption-standards

Is libsodium planning to make a post-quantum-secure `crypto_box` functionality?
For example based on https://openquantumsafe.org/liboqs/ ?

I think this old issue is also related:
https://github.com/jedisct1/libsodium/issues/1082

**Comment by jedisct1** [comment] 2024-12-12 15:54
See the roadmap and other related discussions in the discussions section (issues are for bugs).

A post-quantum hybrid key exchange mechanism, yes, this is planned. Probably based on the Zig implementation. 

But I don't have any need for this, so unless working on it may help pay may rent, I don't know when it will happen.

**Comment by jedisct1** [comment] 2024-12-12 15:54
Closing as this is not a bug.

**Comment by jedisct1** [comment] 2024-12-12 15:54
Closing as this is not a bug.

**Closed** 2024-12-12 15:55 UTC
